import Image from "next/image";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../component/Header";
import About from "../component/About";
import CustomerServices from "../component/CustomerServices";
import VideoSection from "../component/VideoSection";
import Features from "../component/Features";
import WeDo from "../component/WeDo";
import MeetAdvisor from "../component/MeetAdvisor";
import Team from "../component/Team";
import Footer from "../component/Footer";

function Home() {
  return (
    <>
      <Head>
        <title>Rokomari Assingment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* font awesome   */}
        {/* css from brootstrap   */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
          crossOrigin="anonymous"
        />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.2/gsap.min.js"></script>
        <script
          src="https://kit.fontawesome.com/61a6132c09.js"
          crossOrigin="anonymous"
        ></script>
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
          integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
          crossOrigin="anonymous"
        ></link>
      </Head>

      {/* home page start */}
      <>
        <Header />
        <About />
        <CustomerServices />
        <VideoSection />
        <Features />
        <WeDo />
        <MeetAdvisor />
        <Team />
        <Footer />
      </>
      {/* home page end */}
    </>
  );
}
export default Home;
