import Image from "next/image";
import Head from "next/head";
import styles from "../styles/Home.module.css";
 
import About from "../component/About";
import CustomerServices from "../component/CustomerServices";
import VideoSection from "../component/VideoSection";
import Features from "../component/Features";
import WeDo from "../component/WeDo";
import MeetAdvisor from "../component/MeetAdvisor";
import Team from "../component/Team";
 
import Slider from "../component/Slider";

function Home() {
  return (
    <>
      <Head>
        <title>Rokomari Assingment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* home page start */}
      <>






        {/* <Slider />
        
        <About />
        <CustomerServices />
        <VideoSection />
        <Features />
        <WeDo />
        <MeetAdvisor />
        <Team /> */}
      </>
      {/* home page end */}
    </>
  );
}
export default Home;
